services:
  app:
    build: .
    container_name: app_php
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=mysql://root:leandro1@db/app_php
    volumes:
      - .:/var/www/html  # Map the entire project directory
    command: >
      bash -c "composer install --optimize-autoloader && php /var/www/html/update_schema.php && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql_php
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: leandro1
      MYSQL_DATABASE: app_php
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: